### PR TITLE
Upgrade bindings for c++ driver 2.16.0

### PR DESCRIPTION
**Pull request by iredelmeier**
Note: These bindings were built without the existing `rustfmt.toml`, so they may be due for some reformatting if non-default formatting is still desired.

### CODE REVIEW

**Review by kw217 — CHANGES_REQUESTED** [review]
Please could you divide this into one commit that tracks the rustfmt change, and another commit that contains the 2.16.0 changes? Otherwise it's impossible to review.

(Also you'll need to rebase, since I merged #32 ).

Thanks!

**Comment by iredelmeier** [comment]
Sorry about that! Thought I'd already split the change out, but I guess I didn't push the right thing or something. It's rebased now :+1:

**Review by kw217 — CHANGES_REQUESTED** [review]
Hi - sorry for the delay, I was on vacation.

Unfortunately this fix is still one commit, not two. Please can you separate all the changes that arise only from `rustfmt` changes into one commit, and the changes that actually relate to upgrading the bindings to 2.16.0 into another commit? At the moment I can't spot the difference between changes like
```diff
-fn insert_into_collections(session: &mut CassSession, key: &str, items: Vec<&str>) -> Result<(), CassError> {
+fn insert_into_collections(
+    session: &mut CassSession,
+    key: &str,
+    items: Vec<&str>,
+) -> Result<(), CassError> {
```
and actual interesting changes.

You can do this by checking out the current master, running `cargo fmt`, committing that, and then rebasing this change on top of that.

**Comment by kw217** [comment]
Hi @iredelmeier - I've now applied the rustfmt changes to master myself, so if you rebase this PR onto the latest master it should have the same effect as splitting the commit, and then I'll be able to review.

**Comment by kw217** [comment]
Superseded by #39. Closing.

**Pull request closed without merging**
