### PR TITLE
Migrate to DataStax C++ Driver version 2.16.0

### PR DESCRIPTION
**Pull request by alexeiakimov**
The present PR provides:
1. The cassandra.h header files taken from the Data Stax C++ Driver version 2.16.0
2. The new generated C -> Rust bindings, which were generated with `--size_t-is-usize` option to make them compatible with the previous version.
3. A new example `cloud.rs` adapted from the original `cloud.c` example demonstrating how to use cloud secure connection bundle.

### CODE REVIEW

**Review by kw217 — CHANGES_REQUESTED** [review]
Thanks @alexeiakimov - this looks good, I very much appreciate you sorting this! Apologies for the delay.
I won't be able to merge this until I move off Travis to GitHub Actions; then we can rebase this on top of that and merge.
Please can you update the CHANGELOG with an appropriate entry (like the 0.12.0 one)?

**Comment by kw217** [comment]
I've moved to GitHub Actions now - please can you rebase onto master to pick that up? Thanks.

**Comment by alexeiakimov** [comment]
> I've moved to GitHub Actions now - please can you rebase onto master to pick that up? Thanks.

Thank you. Done.

**Comment by alexeiakimov** [comment]
> Thanks @alexeiakimov - this looks good, I very much appreciate you sorting this! Apologies for the delay. I won't be able to merge this until I move off Travis to GitHub Actions; then we can rebase this on top of that and merge. Please can you update the CHANGELOG with an appropriate entry (like the 0.12.0 one)?

Thank you. Done.

**Review by kw217 — APPROVED** [review]
LGTM - thanks!

**Comment by kw217** [comment]
@alexeiakimov I am happy to do a release for this, but it's probably wisest if you make the changes to cassandra-rs first (on a branch, using a git dependency) and confirm it all works before I do that. OK?
I intend to bump to 1.x, to reflect the supported status of this driver (I should have done that ages ago).

**Comment by alexeiakimov** [comment]
@kw217  No problem, I will evaluate it. I will let you know about the result below. Thank you.

**Comment by alexeiakimov** [comment]
The first issue I see is that the generated from the C++ header `CassError_` has two new variants:

1. `CASS_ERROR_LIB_NO_TRACING_ID = 16777251`,
2. `CASS_ERROR_SSL_CLOSED = 50331655`,

which leads to compilation errors, because in cassandra-rs the application of `enhance-nullary-enum!` to `CassErrorCode` needs a mapping for those new variants (see `error.rs` line 245).

I do not think that we can add the new variants to the omit section of the macro application, because it will lead to panic in case of the new variants of the error. So it seems we need to extend CassErrorCode and the corresponding mapping. However extending enums can lead to compilation errors in the existing client code, especially in case when a pattern matching without wildcards is used. @kw217 do you think there is a way adapt the cassandra-rs to the new cassandra-sys-rs without loosing the backward compatibility?

**Comment by kw217** [comment]
I think it has to be a breaking change this time, but we can avoid it being breaking in future by adding `#[non_exhaustive]` to the enum definition per https://doc.rust-lang.org/reference/attributes/type_system.html#the-non_exhaustive-attribute . I'm happy for this to be breaking; it's unlikely many people have exhaustive matches on such a large list of errors and if they do the fix is easy.

**Pull request merged**
