### PR TITLE
Fix up warnings thrown by Clippy

### PR DESCRIPTION
**Pull request by angusi**
This commit leaves a couple of warnings in the examples, where there is
still work to do to complete (or completely update) the example. It also
leaves a warning where there is a missing safety docstring, to flag that
this should still be added.

### CODE REVIEW

**Comment by kw217** [comment]
Thanks. As you say, `cargo clippy --all-targets -- -A clippy::float_cmp` still gives a handful of errors. Any chance you could fix those as well, and update .github/workflows/build.yml to run clippy so they stay fixed? (you could add a `cargo fmt --all --check` as well while you're there).

**Review by kw217 — CHANGES_REQUESTED** [review]
As noted above - changes required.

**Comment by kw217** [comment]
@angusi I've tidied this up myself; please can you review?

**Review by angusi — COMMENTED** [review]
Nice - thanks for finishing this up @kw217. 

I can't click approve, as this is my PR, but I'm happy with your latest changes.

**Review by kw217 — APPROVED** [review]
LGTM, and @angusi states above he's happy too. Approved.

**Pull request merged**
