### PR TITLE
Update underlying C++ driver to 2.8.0

### PR DESCRIPTION
**Pull request by dimbleby**
(Also used newer bindgen for autogen, and newer rustfmt)

We're currently using 2.4.3, which is fifteen months old and a couple of hundred commits behind the latest release.  I've no special reason for upgrading, but sooner or later it wants doing.  After all, the very first sentence of the README does specifically boast that this is a maintained project ...

I'll follow up shortly with a pull in the cassandra-rs repository to match.

### CODE REVIEW

**Review by angusi — APPROVED** [review]
Thanks @dimbleby!
Basically all of this change is either from Datastax upstream or from the resulting new bindgen, right? LGTM.

**Comment by dimbleby** [comment]
> all of this change is either from Datastax upstream or from the resulting new bindgen, right? 

correct

**Comment by kw217** [comment]
LGTM too. Might be nice to create a CHANGELOG to explain what the changes are, since this is a breaking change. The key one we care about I think is that some symbol names have changed:

`cass_error_result_actual` -> `cass_error_result_responses_received`
`cass_error_result_required` -> `cass_error_result_responses_required`

but there may be others.

Edit: also the write type has changed from `UKNOWN` to `UNKNOWN`.

**Comment by dimbleby** [comment]
haha, it seems that I don't have permissions to remove the assignment of this issue to me...

**Comment by kw217** [comment]
Thanks, merged.

**Pull request merged**
